import java.util.ArrayList;
import java.util.List;

public class main {
    public static void main(String[] args) {
        int N = 10;
        System.out.println("the Fibonacci sequence generated by loop method is:");
        loop.Fibonacci(N);

        System.out.println("");
        System.out.println("the Fibonacci sequence generated by recursive method is:");
        for (int i = 0; i < N; i++) {
            System.out.print(recursive.fib(i) + " ");
        }
    }
}
